### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by ffrm** [ffrm/graphlite#1]
- [ ] Document association on README.md;
- [ ] Add mocha to test data from connection using the generated queries;
- [ ] Create and test true examples;
